import { ProductType } from "@/types/types";

export const flashItems: ProductType[] = [
  {
    id: "a1b2c3d4",
    name: "HAVIT HV-G92 Gamepad",
    currentPrice: 120,
    discount: 40,
    rating: 5,
    originalPrice: 160,
    soldTimes: 88,
    imageUrl: "/flashImages/gamepad.svg",
  },
  {
    id: "e5f6a7b8",
    name: "AK-900 Wired Keyboard",
    currentPrice: 960,
    discount: 35,
    originalPrice: 1160,
    rating: 4,
    soldTimes: 75,
    imageUrl: "/flashImages/keyboard.svg",
  },
  {
    id: "c9d0e1f2",
    name: "IPS LCD Gaming Monitor",
    currentPrice: 370,
    discount: 30,
    rating: 5,
    soldTimes: 99,
    imageUrl: "/flashImages/tv.svg",
    originalPrice: 400,
  },
  {
    id: "a3b4c5d6",
    name: "S-Series Comfort Chair ",
    currentPrice: 375,
    discount: 25,
    rating: 4,
    soldTimes: 99,
    originalPrice: 400,
    imageUrl: "/flashImages/chair.svg",
  },
];

export const bestSellingProducts: ProductType[] = [
  {
    id: "e7f8g9h0",
    name: "The north coat",
    currentPrice: 260,
    rating: 5,
    soldTimes: 65,
    originalPrice: 360,
    imageUrl: "/bestSellingImages/tshirt.svg",
  },
  {
    id: "i1j2k3l4",
    name: "Gucci duffle bag",
    originalPrice: 1160,
    currentPrice: 960,
    rating: 4,
    soldTimes: 65,
    imageUrl: "/bestSellingImages/bag.svg",
  },
  {
    id: "m5n6o7p8",
    name: "RGB liquid CPU Cooler",
    originalPrice: 170,
    currentPrice: 160,
    rating: 4,
    soldTimes: 99,
    imageUrl: "/bestSellingImages/cd.svg",
  },
  {
    id: "q9r0s1t2",
    name: "Small BookSelf",
    currentPrice: 360,
    originalPrice: 0,
    rating: 5,
    soldTimes: 65,
    imageUrl: "/bestSellingImages/desk.svg",
  },
];

export const exploreProducts: ProductType[] = [
  {
    id: "u3v4w5x6",
    name: "Breed Dry Dog Food",
    currentPrice: 100,
    originalPrice: 0,
    rating: 5,
    soldTimes: 35,
    imageUrl: "/productImages/dogfood.svg",
  },
  {
    id: "y7z8a9b0",
    name: "CANON EOS DSLR Camera",
    currentPrice: 360,
    rating: 5,
    originalPrice: 0,
    soldTimes: 95,
    imageUrl: "/productImages/camera.svg",
  },
  {
    id: "c1d2e3f4",
    name: "ASUS FHD Gaming Laptop",
    currentPrice: 700,
    originalPrice: 0,
    rating: 5,
    soldTimes: 325,
    imageUrl: "/productImages/laptop.svg",
  },
  {
    id: "g5h6i7j8",
    name: "Curology Product Set",
    currentPrice: 500,
    originalPrice: 0,
    rating: 5,
    soldTimes: 145,
    imageUrl: "/productImages/facewash.svg",
  },
  {
    id: "k9l0m1n2",
    name: "Kids Electric Car",
    currentPrice: 160,
    rating: 5,
    soldTimes: 65,
    originalPrice: 0,
    imageUrl: "/productImages/car.svg",
    colors: ["#FB1314", "#DB4444"],
    isNew: true,
  },
  {
    id: "o3p4q5r6",
    name: "Jr. Zoom Soccer Cleats",
    currentPrice: 1160,
    originalPrice: 0,
    rating: 5,
    soldTimes: 35,
    imageUrl: "/productImages/shoe.svg",
    colors: ["#EEFF61", "#DB4444"],
  },
  {
    id: "s7t8u9v0",
    name: "GP11 Shooter USB Gamepad",
    currentPrice: 660,
    originalPrice: 0,
    rating: 4,
    soldTimes: 55,
    imageUrl: "/productImages/gamepad.svg",
    colors: ["#000000", "#DB4444"],
    isNew: true,
  },
  {
    id: "w1x2y3z4",
    name: "Quilted Satin Jacket",
    currentPrice: 660,
    rating: 4,
    originalPrice: 0,
    soldTimes: 55,
    imageUrl: "/productImages/tshirt.svg",
    colors: ["#000000", "#DB4444"],
  },
];

export const wishlistProducts: ProductType[] = [
  {
    id: "a5b6c7d8",
    name: "Gucci duffle bag",
    originalPrice: 1160,
    currentPrice: 960,
    rating: 4,
    addedToWishlist: true,
    soldTimes: 65,
    imageUrl: "/bestSellingImages/bag.svg",
  },
  {
    id: "e9f0g1h2",
    name: "RGB liquid CPU Cooler",
    originalPrice: 0,
    currentPrice: 160,
    discount: 35,
    addedToWishlist: true,
    rating: 4,
    soldTimes: 99,
    imageUrl: "/bestSellingImages/cd.svg",
  },
  {
    id: "i3j4k5l6",
    name: "GP11 Shooter USB Gamepad",
    currentPrice: 550,
    originalPrice: 0,
    rating: 4,
    soldTimes: 55,
    addedToWishlist: true,
    imageUrl: "/productImages/gamepad.svg",
  },
  {
    id: "m7n8o9p0",
    name: "Quilted Satin Jacket",
    currentPrice: 750,
    rating: 4,
    originalPrice: 0,
    soldTimes: 55,
    addedToWishlist: true,
    imageUrl: "/productImages/tshirt.svg",
  },
];
