import { ProductType } from "@/types/types";

export const flashItems: ProductType[] = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    currentPrice: 120,
    discount: 40,
    rating: 5,
    originalPrice: 160,
    soldTimes: 88,
    imageUrl: "/flashImages/gamepad.svg",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    currentPrice: 960,
    discount: 35,
    originalPrice: 1160,
    rating: 4,
    soldTimes: 75,
    imageUrl: "/flashImages/keyboard.svg",
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    currentPrice: 370,
    discount: 30,
    rating: 5,
    soldTimes: 99,
    imageUrl: "/flashImages/tv.svg",
    originalPrice: 400,
  },
  {
    id: 4,
    name: "S-Series Comfort Chair ",
    currentPrice: 375,
    discount: 25,
    rating: 4,
    soldTimes: 99,
    originalPrice: 400,
    imageUrl: "/flashImages/chair.svg",
  },
];

export const bestSellingProducts: ProductType[] = [
  {
    id: 1,
    name: "The north coat",
    currentPrice: 260,
    rating: 5,
    soldTimes: 65,
    originalPrice: 360,
    imageUrl: "/bestSellingImages/tshirt.svg",
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    originalPrice: 1160,
    currentPrice: 960,
    rating: 4,
    soldTimes: 65,
    imageUrl: "/bestSellingImages/bag.svg",
  },
  {
    id: 3,
    name: "RGB liquid CPU Cooler",
    originalPrice: 170,
    currentPrice: 160,
    rating: 4,
    soldTimes: 99,
    imageUrl: "/flashImages/cd.svg",
  },
  {
    id: 4,
    name: "Small BookSelf",
    originalPrice: 360,
    rating: 5,
    soldTimes: 65,
    imageUrl: "/flashImages/desk.svg",
  },
];

export const exploreProducts: ProductType[] = [
  {
    id: 1,
    name: "Breed Dry Dog Food",
    originalPrice: 100,
    rating: 5,
    soldTimes: 35,
    imageUrl: "/productImages/dogfood.svg",
  },
  {
    id: 2,
    name: "CANON EOS DSLR Camera",
    originalPrice: 360,
    rating: 5,
    soldTimes: 95,
    imageUrl: "/productImages/camera.svg",
  },
  {
    id: 3,
    name: "ASUS FHD Gaming Laptop",
    originalPrice: 700,
    rating: 5,
    soldTimes: 325,
    imageUrl: "/productImages/laptop.svg",
  },
  {
    id: 4,
    name: "Curology Product Set",
    originalPrice: 500,
    rating: 5,
    soldTimes: 145,
    imageUrl: "/productImages/facewash.svg",
  },
  {
    id: 5,
    name: "Kids Electric Car",
    originalPrice: 160,
    rating: 5,
    soldTimes: 65,
    imageUrl: "/productImages/car.svg",
    colors: ["#FB1314", "#DB4444"],
  },
  {
    id: 6,
    name: "Jr. Zoom Soccer Cleats",
    originalPrice: 1160,
    rating: 5,
    soldTimes: 35,
    imageUrl: "/productImages/shoe.svg",
    colors: ["#EEFF61", "#DB4444"],
  },
  {
    id: 7,
    name: "GP11 Shooter USB Gamepad",
    originalPrice: 660,
    rating: 4,
    soldTimes: 55,
    imageUrl: "/productImages/gamepad.svg",
    colors: ["#000000", "#DB4444"],
  },
  {
    id: 8,
    name: "Quilted Satin Jacket",
    originalPrice: 660,
    rating: 4,
    soldTimes: 55,
    imageUrl: "/productImages/tshirt.svg",
    colors: ["#000000", "#DB4444"],
  },
];
